version: '3.8'

services:
  llm-dev:
    image: llm-env:latest
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - llm-env:cache
      args:
        BUILDKIT_INLINE_CACHE: 1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./workspace:/mnt
      - uv-cache:/opt/uv-cache
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - CUDA_VISIBLE_DEVICES=all
      - HF_HOME=/root/.cache/huggingface
    shm_size: '64gb'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    stdin_open: true
    tty: true
    command: /bin/bash

volumes:
  uv-cache:
    driver: local