# CUDA-PyTorchの互換性マップ（2025年6月版）
# 情報源: https://pytorch.org/get-started/previous-versions/ + 調査結果
cuda:
  "12.8":
    compatible_pytorch: ["2.7.0"]
    index_url: "https://download.pytorch.org/whl/cu128"
    stability: "cutting_edge"
  "12.6":
    compatible_pytorch: ["2.7.0", "2.6.0"]
    index_url: "https://download.pytorch.org/whl/cu126"
    stability: "latest"
  "12.4":
    compatible_pytorch: ["2.7.0", "2.6.0", "2.5.1", "2.5.0", "2.4.1", "2.4.0"]
    index_url: "https://download.pytorch.org/whl/cu124"
    stability: "stable"
  "12.1":
    compatible_pytorch: ["2.5.1", "2.5.0", "2.4.1", "2.4.0", "2.3.1", "2.3.0", "2.2.2", "2.2.1", "2.2.0", "2.1.2", "2.1.1", "2.1.0", "2.0.1", "2.0.0"]
    index_url: "https://download.pytorch.org/whl/cu121"
    stability: "stable"
  "11.8":
    compatible_pytorch: ["2.5.1", "2.5.0", "2.4.1", "2.4.0", "2.3.1", "2.3.0", "2.2.2", "2.2.1", "2.2.0", "2.1.2", "2.1.1", "2.1.0", "2.0.1", "2.0.0", "1.13.1", "1.13.0"]
    index_url: "https://download.pytorch.org/whl/cu118"
    stability: "maximum_compatibility"

# PyTorchバージョンの推奨度
pytorch_recommendations:
  "2.7.0":
    status: "latest"
    python_support: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    recommended_cuda: ["12.6", "12.8"]
  "2.5.1":
    status: "stable"
    python_support: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    recommended_cuda: ["11.8", "12.1", "12.4"]
  "2.4.1":
    status: "compatibility"
    python_support: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    recommended_cuda: ["11.8", "12.1"]

# 自動解決用の選択ルール
resolution_rules:
  prefer_stability: ["11.8", "12.1", "12.4", "12.6", "12.8"]
  prefer_performance: ["12.8", "12.6", "12.4", "12.1", "11.8"]
  prefer_compatibility: ["11.8", "12.1", "12.4", "12.6", "12.8"]