# CUDA-PyTorchの互換性マップ
# 情報源: https://pytorch.org/get-started/previous-versions/
cuda:
  "12.9":
    compatible_pytorch: ["2.7.0", "2.6.0", "2.5.0"]
  "12.8":
    compatible_pytorch: ["2.7.0", "2.6.0", "2.5.0", "2.4.0"]
  "12.6.3":
    compatible_pytorch: ["2.7.0", "2.6.0", "2.5.0", "2.4.0"]
  "12.4":
    compatible_pytorch: ["2.7.0", "2.6.0", "2.5.0", "2.4.0", "2.3.0"]
  "12.1":
    compatible_pytorch: ["2.7.0", "2.6.0", "2.5.0", "2.4.0", "2.3.0", "2.2.0", "2.1.0", "2.0.0"]
  "11.8":
    compatible_pytorch: ["2.5.0", "2.4.0", "2.3.0", "2.2.0", "2.1.0", "2.0.0", "1.13.1", "1.13.0", "1.12.1"]