# Transformersの互換性マップ
# 情報源: https://github.com/huggingface/transformers/releases
transformers:
  "4.41.0":
    requires_pytorch: ">=1.10.0"
    compatible_cuda: ["11.1", "11.2", "11.3", "11.4", "11.5", "11.6", "11.7", "11.8", "12.0", "12.1", "12.2"]
  "4.37.0":
    requires_pytorch: ">=1.10.0"
    compatible_cuda: ["11.1", "11.2", "11.3", "11.4", "11.5", "11.6", "11.7", "11.8", "12.0", "12.1"]
  "4.34.0":
    requires_pytorch: ">=1.10.0"
    compatible_cuda: ["11.1", "11.2", "11.3", "11.4", "11.5", "11.6", "11.7", "11.8", "12.0"]
  "4.30.0":
    requires_pytorch: ">=1.10.0"
    compatible_cuda: ["11.1", "11.2", "11.3", "11.4", "11.5", "11.6", "11.7", "11.8"]