# PyTorch-Pythonの互換性マップ
# 情報源: https://pytorch.org/get-started/previous-versions/
pytorch:
  "2.2.0":
    compatible_python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
  "2.1.0":
    compatible_python: ["3.8", "3.9", "3.10", "3.11"]
  "2.0.0":
    compatible_python: ["3.8", "3.9", "3.10", "3.11"]
  "1.13.1":
    compatible_python: ["3.7", "3.8", "3.9", "3.10"]
  "1.12.0":
    compatible_python: ["3.7", "3.8", "3.9", "3.10"]