# TRL（Transformer Reinforcement Learning）の互換性マップ
# 情報源: https://github.com/huggingface/trl/releases
trl:
  "0.17.0":
    requires_pytorch: ">=2.0.0"
    requires_transformers: ">=4.40.0"
    compatible_cuda: ["11.8", "12.1", "12.4", "12.6.3", "12.8", "12.9"]
  "0.8.6":
    requires_pytorch: ">=1.13.1"
    requires_transformers: ">=4.40.0"
    compatible_cuda: ["11.6", "11.7", "11.8", "12.0", "12.1"]
  "0.7.6":
    requires_pytorch: ">=1.13.1"
    requires_transformers: ">=4.34.0"
    compatible_cuda: ["11.6", "11.7", "11.8", "12.0"]
  "0.6.0":
    requires_pytorch: ">=1.13.1"
    requires_transformers: ">=4.31.0"
    compatible_cuda: ["11.6", "11.7", "11.8", "12.0"]
  "0.5.0":
    requires_pytorch: ">=1.13.1"
    requires_transformers: ">=4.29.0"
    compatible_cuda: ["11.6", "11.7", "11.8"]