# デフォルト設定（uv対応版）
base:
  image: "nvcr.io/nvidia/pytorch"
  tag: "25.05-py3"
  cuda_version: "12.8"
  python_version: "3.10"

# uv設定（新規追加）
uv:
  install_method: "standalone"  # standalone, pipx, direct_pip
  version: "latest"
  cache_size_limit: "10GB" 

gpu:
  architecture: "hopper"
  count: 1
  multi_node: false
  nodes: 1
  optimization: true

deep_learning:
  pytorch:
    version: "2.7.0"
    source: "pip"
    cuda_specific: true
    extras: ["torchvision", "torchaudio"]
  
  attention:
    flash_attention: true
    flash_attention_version: "2.8.0.post2"
    xformers: true
    xformers_version: "0.0.30"
    triton: false

claude_code:
  install: true
  version: "latest"
  nodejs_version: "lts"

libraries:
  use_preset: true
  preset: "standard"

environment:
  preset:
    hopper: true
    multi_gpu: false
  
  custom: []

workspace:
  directory: "/mnt"

distributed:
  enable: false
  backend: "nccl"
  init_method: "env://"

build:
  parallel_jobs: "auto" 
  memory_limit: "8GB"
  cache_cleanup: true