# デフォルト設定
base:
  image: "nvcr.io/nvidia/pytorch"
  tag: "25.05-py3"
  cuda_version: "12.8"
  python_version: "3.10"

gpu:
  architecture: "hopper"
  count: 1
  multi_node: false
  nodes: 1
  optimization: true

deep_learning:
  pytorch:
    version: "2.7.0"
    source: "pip"
    cuda_specific: true
    extras: ["torchvision", "torchaudio"]
  
  attention:
    flash_attention: true
    flash_attention_version: "2.7.4.post1"
    xformers: true
    xformers_version: "0.0.30"
    triton: false

claude_code:
  install: true
  version: "latest"

libraries:
  use_preset: true
  preset: "standard"

environment:
  preset:
    hopper: true
    multi_gpu: false
  
  custom: []

workspace:
  directory: "/mnt"

distributed:
  enable: false
  backend: "nccl"
  init_method: "env://"